import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";

const comfortaa = localFont({
  src: [
    {
      path: "../../public/fonts/comfortaa/comfortaa-latin-300-normal.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/comfortaa/comfortaa-latin-400-normal.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/comfortaa/comfortaa-latin-500-normal.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/comfortaa/comfortaa-latin-600-normal.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/comfortaa/comfortaa-latin-700-normal.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-sans",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import ReactQueryProvider from "@/providers/ReactQueryProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", comfortaa.variable, geistMono.variable, "font-sans")}
    >
      <body className="bg-olive-950 min-h-screen text-white flex flex-col">
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
